spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

#  cache:
#    type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379